### ISSUE TITLE
add "phone" flair

### ISSUE THREAD

**Issue by amitkeret** [balazsorban44/google-calendar-web-material#8]
`['phone', 'phonecall', 'reach', 'contact'],`

![screenshot_20170312-090325](https://cloud.githubusercontent.com/assets/1258597/23828217/d4d6cbe6-0716-11e7-9294-eab5b98c0505.png)

**Comment by balazsorban44** [comment]
I added the extra keywords now.

**Comment by amitkeret** [comment]
Thanks!
May I ask where do you find the original art for the flairs?
I've searched online and in the APK and couldn't find it...

**Comment by balazsorban44** [comment]
It takes a little bit of a work... I take a screenshot just like you did, and then use Photoshop to remove the title, the three dots and the ☓ in the corner.
