### ISSUE TITLE
additional flairs + keywords from android app

### ISSUE THREAD

**Issue by amitkeret** [balazsorban44/google-calendar-web-material#9]
Hi,

I found a file in the APK named "flairdata_en_GB.pb", under "assets > flairs".
It's a list of many keywords, and most of them have their own official flair.
(I'm actually shocked by the number of unique flairs available!)

Would be great if you could add these.
I would be happy to help and create PRs, but I can't find a resource containing the original artwork.

**Comment by balazsorban44** [comment]
It was a long time ago I have updated the event flairs list, I see now, they added much more.
You are welcome to help expanding the keyword list.

The keywords are stored in a two-dimensional array [here](https://github.com/balazsorban44/google-calendar-web-material/blob/master/app/languages/events-EN.js), every line is a different event flair, where the first element (lines are sorted alphabetically according to the first element) in the line defines the name of the image in the [event-flairs](https://github.com/balazsorban44/google-calendar-web-material/tree/master/app/images/event-flairs) folder. The cleaned image is stored there as a png, with size of 1080px * 624px.

**Comment by eslamsayed** [comment]
Some event-flairs pictures are not existed in the array keyword. Do you have any explanation for that and how we can trigger those flairs? Thanks.

**Comment by balazsorban44** [comment]
Hi @eslamsayed . This project is inactive at the moment, as Google announced an official material design to the Google Calendar, which will soon be forced onto everybody. [http://mashable.com/2018/01/03/google-calendar-update-goes-into-effect-in-2018](http://mashable.com/2018/01/03/google-calendar-update-goes-into-effect-in-2018)

Therefore I cannot provide any info right now, as the project should be rewritten from the scratch to work with the new design.
